/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

/*
#include <stdint.h>
// register address

#define RCC_BASE 0x40021000
#define PortA_BASE 0x40010800

#define RCC_APB2ENR *((volatile uint32_t *) (RCC_BASE + 0x18))
#define GPIOA_CRH 	*((volatile uint32_t *) (PortA_BASE + 0x04))
#define GPIOA_ODR 	*((volatile uint32_t *) (PortA_BASE + 0x0C))

int main(void)
{

	RCC_APB2ENR |= 1<<2 ; //put 1 on  the 2nd LSB
	GPIOA_CRH &= 0xff0fffff ; // put zeros on bits 20 >> 23 and keep the other bits as they are
	GPIOA_CRH |= 0x00200000 ; // put 0010 on bits 20 >> 23
	while(1)
	{
		GPIOA_ODR |= 1<<13 ; //set pin 13 = 1
		for( int i = 0 ; i < 90000 ; i++ ); // delay
		GPIOA_ODR &= ~(1<<13) ; //set pin 13 = 0
		for( int i = 0 ; i < 90000 ; i++ ); // delay
	}
	return 0;
}
 */


#include "stdint.h"
// register address
typedef volatile unsigned int vint32_t;

#define RCC_BASE 0x40021000
#define PortA_BASE 0x40010800

#define RCC_APB2ENR *((volatile uint32_t *) (RCC_BASE + 0x18))
#define GPIOA_CRH 	*((volatile uint32_t *) (PortA_BASE + 0x04))
#define GPIOA_ODR 	*((volatile uint32_t *) (PortA_BASE + 0x0C))

typedef union {

	vint32_t all_fields ;
	struct {
		vint32_t reserved:13; //ignore 1st 13 bits : from bit 0 to bit 12
		vint32_t pin13:1;
	}pin;
} R_ODR_t  ; //we put here _t to say that it is a typedef

volatile R_ODR_t* R_ODR = (volatile R_ODR_t*)(PortA_BASE + 0x0C);


int main(void)
{

	RCC_APB2ENR |= 1<<2 ; //put 1 on  the 2nd LSB
	GPIOA_CRH &= 0xff0fffff ; // put zeros on bits 20 >> 23 and keep the other bits as they are
	GPIOA_CRH |= 0x00200000 ; // put 0010 on bits 20 >> 23
	while(1)
	{
		R_ODR -> pin.pin13 = 1; //set pin 13 = 1
		for( int i = 0 ; i < 90000 ; i++ ); // delay

		R_ODR  -> pin.pin13 = 0; //set pin 13 = 0
		for( int i = 0 ; i < 90000 ; i++ ); // delay
	}
	return 0;
}

